// GENERATED by scripts/gen_chrome_bridge.py — do not edit by hand.
// Allowlist: official airline domains from the flight airline catalog.
export const approvedHosts = new Map([
  ['et.airchina.com.cn', 'CA'],
  ['extra.csair.com', 'CZ'],
  ['ffp.airchina.com.cn', 'CA'],
  ['skypearl.csair.com', 'CZ'],
  ['www.9air.com', 'AQ'],
  ['www.airchina.com.cn', 'CA'],
  ['www.airguilin.com', 'GT'],
  ['www.airhunanair.com', 'A6'],
  ['www.airjiangxi.com', 'RY'],
  ['www.airkunming.com', 'KY'],
  ['www.beijingair.com', 'B0'],
  ['www.cdal.com.cn', 'EU'],
  ['www.ceair.com', 'FM'],
  ['www.cgzair.com', 'GY'],
  ['www.ch.com', '9C'],
  ['www.changan-air.com', '9H'],
  ['www.chinaexpressair.com', 'G5'],
  ['www.csair.com', 'CZ'],
  ['www.donghaiair.com', 'DZ'],
  ['www.flycua.com', 'KN'],
  ['www.fuzhou-air.com', 'FU'],
  ['www.gxairlines.com', 'GX'],
  ['www.hainanairlines.com', 'CN'],
  ['www.hbhk.com.cn', 'NS'],
  ['www.jdair.net', 'JD'],
  ['www.joy-air.com', 'JR'],
  ['www.juneyaoair.com', 'HO'],
  ['www.longjiangairlines.com', 'LT'],
  ['www.loongair.cn', 'GJ'],
  ['www.luckyair.net', '8L'],
  ['www.okair.net', 'BK'],
  ['www.qdairlines.com', 'QW'],
  ['www.ruili.com', 'DR'],
  ['www.sda.cn', 'SC'],
  ['www.shenzhenair.com', 'ZH'],
  ['www.sichuanair.com', '3U'],
  ['www.suparnaairlines.com', 'Y8'],
  ['www.tianjiaoair.com', '9D'],
  ['www.tianjin-air.com', 'GS'],
  ['www.tibetairlines.com.cn', 'TV'],
  ['www.urumqi-air.com', 'UQ'],
  ['www.westair.cn', 'PN'],
  ['www.xiamenair.com', 'MF'],
]);

export function officialAirlineUrl(value) {
  try {
    const url = new URL(value);
    return url.protocol === 'https:' && approvedHosts.has(url.hostname) ? url : null;
  } catch {
    return null;
  }
}

export function airlineForHost(host) {
  return approvedHosts.get(host) || null;
}
