"""Event type registry (§6)."""
from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"

    WATCH_STARTED = "WATCH_STARTED"
    WATCH_PAUSED = "WATCH_PAUSED"
    WATCH_RESUMED = "WATCH_RESUMED"
    WATCH_EXPIRED = "WATCH_EXPIRED"

    SCAN_REQUESTED = "SCAN_REQUESTED"
    SCAN_COMPLETED = "SCAN_COMPLETED"

    RAW_LISTING_DISCOVERED = "RAW_LISTING_DISCOVERED"

    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    CANDIDATE_UPDATED = "CANDIDATE_UPDATED"

    OFFER_DISCOVERED = "OFFER_DISCOVERED"
    QUOTE_OBSERVED = "QUOTE_OBSERVED"

    VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"

    SCORE_UPDATED = "SCORE_UPDATED"

    MATERIAL_CHANGE_DETECTED = "MATERIAL_CHANGE_DETECTED"

    OPPORTUNITY_DETECTED = "OPPORTUNITY_DETECTED"

    NOTIFICATION_REQUESTED = "NOTIFICATION_REQUESTED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"

    ACTION_PLAN_CREATED = "ACTION_PLAN_CREATED"

    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"

    ACTION_EXECUTION_REQUESTED = "ACTION_EXECUTION_REQUESTED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"

    MEMORY_UPDATE_REQUESTED = "MEMORY_UPDATE_REQUESTED"
    MEMORY_UPDATED = "MEMORY_UPDATED"

    # system/observability
    EVENT_FAILED = "EVENT_FAILED"
