#!/usr/bin/env python3
"""Generate the Chrome Session Bridge extension from the flight airline catalog.

Why a generator: the extension's allowlist (host_permissions + bridge-policy)
MUST stay in sync with `domains/flight/airports.py` AIRLINE_CATALOG. Hand-editing
two copies drifts; generating keeps one source of truth.

Usage (from repo root `universal-agent/`):
    ../.venv/bin/python scripts/gen_chrome_bridge.py

Output: `universal_agent/adapters/browser/chrome_bridge/`
  - manifest.json        (MV3; host_permissions = allowlist; external connect = local app)
  - bridge-policy.mjs    (host → airline code map, consumed by background.js)
  - background.js        (default-deny: only approved https hosts, no cookies/passwords)
  - popup.html           (status display)
  - README.md            (one-time manual install + strict boundaries)

SPAC §33: the bridge only OPENS official pages in the user's own Chrome profile;
it never reads cookies/passwords/forms/captcha/payment. User keeps login state.
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import urlparse

from universal_agent.adapters.browser.bridge import EXTRA_OFFICIAL_HOSTS
from universal_agent.domains.flight.airports import AIRLINE_CATALOG

OUT_DIR = Path(__file__).resolve().parent.parent / "universal_agent" / "adapters" / "browser" / "chrome_bridge"

#: 本地应用源（看板/CLI）—— 扩展只接受来自这里的消息
APP_ORIGIN = "http://127.0.0.1:8632"


def _host_to_airline() -> dict:
    """官方域名 → 主航司 IATA（同域多航司取 IATA 最小的一个作为展示码）。"""
    mapping: dict = {}
    for iata, info in AIRLINE_CATALOG.items():
        host = urlparse(info["official_url"]).hostname
        if not host:
            continue
        if host not in mapping or iata < mapping[host]:
            mapping[host] = iata
    for host in EXTRA_OFFICIAL_HOSTS:
        if host.startswith(("ffp.", "et.")):
            mapping[host] = "CA"
        elif host.startswith(("skypearl.", "extra.")):
            mapping[host] = "CZ"
    return dict(sorted(mapping.items()))


def _manifest(hosts: list) -> dict:
    return {
        "manifest_version": 3,
        "name": "Universal Agent Official Session Bridge",
        "version": "0.1.0",
        "description": ("Opens allowlisted airline official pages from Universal Agent "
                        "without accessing passwords, cookies, or payment data."),
        "permissions": ["tabs"],
        "host_permissions": [f"https://{h}/*" for h in hosts],
        "background": {"service_worker": "background.js", "type": "module"},
        "action": {"default_title": "Universal Agent Session Bridge",
                   "default_popup": "popup.html"},
        "externally_connectable": {"matches": [f"{APP_ORIGIN}/*"]},
    }


def _policy_js(mapping: dict) -> str:
    lines = "\n".join(f"  ['{host}', '{iata}']," for host, iata in mapping.items())
    return (
        "// GENERATED by scripts/gen_chrome_bridge.py — do not edit by hand.\n"
        "// Allowlist: official airline domains from the flight airline catalog.\n"
        "export const approvedHosts = new Map([\n"
        f"{lines}\n"
        "]);\n\n"
        "export function officialAirlineUrl(value) {\n"
        "  try {\n"
        "    const url = new URL(value);\n"
        "    return url.protocol === 'https:' && approvedHosts.has(url.hostname) ? url : null;\n"
        "  } catch {\n"
        "    return null;\n"
        "  }\n"
        "}\n\n"
        "export function airlineForHost(host) {\n"
        "  return approvedHosts.get(host) || null;\n"
        "}\n"
    )


BACKGROUND_JS = """// GENERATED template (logic stable; allowlist lives in bridge-policy.mjs).
import { airlineForHost, officialAirlineUrl } from './bridge-policy.mjs';

const localAppOrigin = '{APP_ORIGIN}';

function isApprovedSender(sender) {{
  try {{
    return new URL(sender.url).origin === localAppOrigin;
  }} catch {{
    return false;
  }}
}}

function errorResponse(error) {{
  return {{ ok: false, error }};
}}

chrome.runtime.onMessageExternal.addListener((message, sender, sendResponse) => {{
  if (!isApprovedSender(sender)) {{
    sendResponse(errorResponse('UNAUTHORIZED_ORIGIN'));
    return;
  }}

  if (!message || typeof message.type !== 'string') {{
    sendResponse(errorResponse('INVALID_MESSAGE'));
    return;
  }}

  if (message.type === 'ping') {{
    sendResponse({{ ok: true, version: chrome.runtime.getManifest().version }});
    return;
  }}

  if (message.type === 'launchOfficial') {{
    const url = officialAirlineUrl(message.url);
    if (!url) {{
      sendResponse(errorResponse('UNAPPROVED_AIRLINE_URL'));
      return;
    }}
    chrome.tabs.create({{ url: url.href, active: true }})
      .then((tab) => sendResponse({{ ok: true, tab: {{ id: tab.id, host: url.hostname, airline: airlineForHost(url.hostname) }} }}))
      .catch(() => sendResponse(errorResponse('TAB_CREATE_FAILED')));
    return true;
  }}

  if (message.type === 'getOpenAirlineTabs') {{
    chrome.tabs.query({{}})
      .then((tabs) => tabs.flatMap((tab) => {{
        const url = officialAirlineUrl(tab.url || '');
        return url ? [{{ id: tab.id, host: url.hostname, airline: airlineForHost(url.hostname) }}] : [];
      }}))
      .then((tabs) => sendResponse({{ ok: true, tabs }}))
      .catch(() => sendResponse(errorResponse('TAB_QUERY_FAILED')));
    return true;
  }}

  sendResponse(errorResponse('UNSUPPORTED_ACTION'));
}});
"""

POPUP_HTML = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<title>Universal Agent Session Bridge</title>
<style>
  body { font-family: system-ui, sans-serif; width: 260px; padding: 12px; }
  h1 { font-size: 14px; margin: 0 0 8px; }
  p { font-size: 12px; color: #555; line-height: 1.5; margin: 4px 0; }
  .ok { color: #1a7f37; font-weight: 600; }
</style>
</head>
<body>
<h1>🛡️ Universal Agent 官方会话桥</h1>
<p>扩展已就绪。它只负责在<b>你本人的 Chrome</b> 中打开已批准的白名单航司官方页面。</p>
<p class="ok">✓ 不读取 Cookie / 密码 / 表单 / 网页内容 / 支付信息</p>
<p>登录、验证码、MFA 与付款始终由你在航司官网亲自完成。</p>
</body>
</html>
"""

README_MD = """# Universal Agent 官方会话桥（Chrome 扩展）

让 Universal Agent 在**你本人的 Chrome 个人资料**中打开白名单航司官方页面，
航司登录态由 Chrome 自己保持（可用 Chrome 密码管理器自动填充）。

> 由 `scripts/gen_chrome_bridge.py` 从航司名录生成；白名单变更后重新运行该脚本。

## 安装（只需一次，需你本人操作）

1. Chrome 打开 `chrome://extensions`，开启右上角“开发者模式”。
2. 点击“加载已解压的扩展程序”，选择本目录 `chrome_bridge` 文件夹。
3. 复制 Chrome 显示的扩展程序 ID（可选，供本地应用校验）。
4. 在浏览器打开本地看板（默认 `http://127.0.0.1:8632`），使用“官方会话”功能，
   每次打开官方页面都会先请求你批准（默认拒绝，RULE-007）。

## 严格边界（不可移除）

- **不申请 `cookies` 权限**，不读取、导出或同步 Cookie。
- 不读取 Chrome 密码管理器、保存的密码、网页表单或网页内容。
- 只接受来自本地应用源（`externally_connectable`）的消息，且只可打开
  预先批准的 HTTPS 官方域名（见 `bridge-policy.mjs`）。
- 不处理支付字段，不点击确认付款，不提交购买（SPAC §33 非目标）。
"""


def main() -> None:
    mapping = _host_to_airline()
    hosts = list(mapping.keys())
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUT_DIR / "manifest.json").write_text(
        json.dumps(_manifest(hosts), ensure_ascii=False, indent=2) + "\n", "utf-8")
    (OUT_DIR / "bridge-policy.mjs").write_text(_policy_js(mapping), "utf-8")
    (OUT_DIR / "background.js").write_text(
        BACKGROUND_JS.replace("{APP_ORIGIN}", APP_ORIGIN), "utf-8")
    (OUT_DIR / "popup.html").write_text(POPUP_HTML, "utf-8")
    (OUT_DIR / "README.md").write_text(README_MD, "utf-8")

    print(f"chrome_bridge generated: {len(hosts)} allowlisted hosts → {OUT_DIR}")
    for host, iata in mapping.items():
        print(f"  {host}  ({iata})")


if __name__ == "__main__":
    main()
