"""Repository Protocol（P1.1）— 领域存储抽象基类。

SQLite 是第一实现；将来可换 PostgreSQL/其他，业务代码只依赖这些协议。
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

from ..core.contracts import ScanRun, WatchTask


class TaskRepository(ABC):
    @abstractmethod
    def create(self, task: WatchTask) -> WatchTask: ...
    @abstractmethod
    def update(self, task: WatchTask) -> WatchTask: ...
    @abstractmethod
    def get(self, task_id: str) -> Optional[WatchTask]: ...
    @abstractmethod
    def list(self) -> List[WatchTask]: ...
    @abstractmethod
    def delete(self, task_id: str) -> bool: ...
    @abstractmethod
    def active_watches(self) -> List[WatchTask]: ...
    @abstractmethod
    def due_tasks_utc(self, now) -> List[str]: ...


class ScanRunRepository(ABC):
    @abstractmethod
    def start(self, task_id: str, trace_id: Optional[str] = None,
              attempt: int = 1) -> ScanRun: ...
    @abstractmethod
    def finish(self, run_id: str, status, error_type=None,
               error_message=None) -> ScanRun: ...
    @abstractmethod
    def retryable(self) -> List[ScanRun]: ...
    @abstractmethod
    def latest_for(self, task_id: str) -> Optional[ScanRun]: ...
    @abstractmethod
    def list_all(self) -> List[ScanRun]: ...


class EventRepository(ABC):
    @abstractmethod
    def append(self, event: Any) -> None: ...
    @abstractmethod
    def list_for(self, task_id: Optional[str] = None, limit: int = 100) -> List[Any]: ...


class OutboxRepository(ABC):
    @abstractmethod
    def enqueue(self, event: Any) -> int: ...
    @abstractmethod
    def pending(self, limit: int = 100) -> List[Dict[str, Any]]: ...
    @abstractmethod
    def mark_delivered(self, outbox_id: int) -> None: ...
    @abstractmethod
    def mark_dead(self, outbox_id: int, error: str) -> None: ...


class ObservationRepository(ABC):
    @abstractmethod
    def record(self, observation: Any) -> Any: ...
    @abstractmethod
    def price_history(self, target_key: str) -> List[float]: ...
    @abstractmethod
    def list_all(self) -> List[Any]: ...


class MemoryRepository(ABC):
    @abstractmethod
    def put(self, scope, key, value, **kw) -> Any: ...
    @abstractmethod
    def get(self, scope, key, **kw) -> Optional[Any]: ...
    @abstractmethod
    def query(self, q) -> List[Any]: ...


class NotificationRepository(ABC):
    @abstractmethod
    def record(self, fingerprint: str, task_id: str, state: Dict[str, Any]) -> None: ...
    @abstractmethod
    def get(self, fingerprint: str) -> Optional[Dict[str, Any]]: ...


class ApprovalRepository(ABC):
    @abstractmethod
    def request(self, approval: Dict[str, Any]) -> Dict[str, Any]: ...
    @abstractmethod
    def update(self, approval_id: str, **kw) -> Dict[str, Any]: ...
    @abstractmethod
    def find(self, approval_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def pending(self) -> List[Dict[str, Any]]: ...


class ActionRepository(ABC):
    @abstractmethod
    def save_plan(self, plan: Any) -> None: ...
    @abstractmethod
    def save_execution(self, execution: Dict[str, Any]) -> None: ...
    @abstractmethod
    def list_executions(self, task_id: Optional[str] = None) -> List[Dict[str, Any]]: ...


class AuditRepository(ABC):
    @abstractmethod
    def record(self, entry: Dict[str, Any]) -> None: ...
    @abstractmethod
    def entries(self, limit: Optional[int] = None) -> List[Dict[str, Any]]: ...


class SourceHealthRepository(ABC):
    @abstractmethod
    def set(self, marketplace_id: str, health: Dict[str, Any]) -> None: ...
    @abstractmethod
    def get(self, marketplace_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def list(self) -> List[Dict[str, Any]]: ...
